---
title: "Whale-shark Al-lith"
output:
  word_document: default
subtitle: Supplementary information
---

# Model results

```{r, echo = FALSE, message = FALSE}
library(dplyr)
library(gamm4)
library(stringr)

ma <- readRDS("./data/processed/results_window6/models_acoustic_fixed.rds")
mv <- readRDS("data/processed/results_window6/models_visual_fixed.rds")

remove_errors <- . %>% plyr::llply(function(x){
  if(any(class(x) == "try-error")){
    return(NULL)
  } else (
    return(x)
  )
})

ma <- remove_errors(ma)
ma[sapply(ma, is.null)] <- NULL

mv <- remove_errors(mv)
mv[sapply(mv, is.null)] <- NULL
```

```{r, echo = FALSE}
aictable <- . %>% plyr::ldply(function(x){
  data_frame(f = as.character(formula(x$gam)[3])) %>% 
    bind_cols(broom::glance(x[[1]]))
})

aictable(ma) %>% 
  mutate(f = str_replace(f, "\\(([^)]+)\\)", "eason"), 
         f = str_replace(f, "s\\(([^)]+)\\)", "lag"),
         f = str_replace(f, "nStations_inshore", "effort (IS)"), 
         f = str_replace(f, "nStations_offshore", "effort (OS)"),
         delta_AIC = AIC - min(AIC), 
         AIC = round(AIC, 2), 
         delta_AIC = round(delta_AIC, 2)) %>%
  arrange(delta_AIC) %>%
  rename(`$\\Delta$AIC` = delta_AIC, 
         model = f) %>%
  select(-sigma, - df.residual, -deviance) %>%
  mutate_at(.vars = vars(logLik, AIC, BIC), 
            .funs = funs(round, .args = list(digits = 1))) %>%
  knitr::kable(caption = "Table 1. Model selection table for the acoustic recaptures")
```

```{r, echo = FALSE}
aictable(mv) %>% 
  mutate(f = str_replace(f, "\\(([^)]+)\\)", "eason"), 
         f = str_replace(f, "s\\(([^)]+)\\)", "lag"),
         f = str_replace(f, "hours", "effort"),
         delta_AIC = AIC - min(AIC), 
         AIC = round(AIC, 2), 
         delta_AIC = round(delta_AIC, 2)) %>%
 arrange(delta_AIC) %>%
  rename(`$\\Delta$AIC` = delta_AIC, 
         model = f) %>%
  dplyr::select(-sigma, - deviance) %>%
  mutate_at(.vars = vars(logLik, AIC, BIC), 
            .funs = funs(round, .args = list(digits = 1))) %>%  knitr::kable(caption = "Table 2. Model selection table for the visual recaptures")
```

```{r, echo = FALSE}
library(broom)

best_models <- list(
  acoustic = ma[[aictable(ma)$AIC %>% which.min()]], 
  visual = mv[[aictable(mv)$AIC %>% which.min()]]
)

extract_vals <- function(x) {
  terms.smooth <- summary(x$gam)$s.table  %>%
    as.data.frame() %>% 
    tibble::rownames_to_column()
  names(terms.smooth)[c(2, 4)] <- c("Stat.", "EDF")
  # %>%
  #   rename(Stat. = Chi.sq, 
  #          EDF = edf)
  terms.fixed <- summary(x$gam)$p.table %>%
     as.data.frame() %>% 
    tibble::rownames_to_column()
  names(terms.fixed)[c(4, 5)] <- c("Stat.", "p-value")
# 
#   %>%
#     rename(Stat. = `z value`,
#            `p-value` = `Pr(>|z|)`)
  bind_rows(terms.fixed, terms.smooth) %>%
    rename(variable = rowname) %>%
    select(variable, EDF, Estimate, `Std. Error`, Stat., `p-value`) 
}

extract_vals(best_models$acoustic) %>% 
  mutate(variable = if_else(variable == "s(week.2)", "season", variable),
         variable = str_replace(variable, "nStations_inshore", "effort (IS)"),
         variable = if_else(variable == "s(lag)", "lag", variable)) %>%
  knitr::kable(caption = "Table 3. Model results for the most best model of acoustic recapture")
```

```{r, echo = FALSE}
extract_vals(best_models$visual) %>% 
  mutate(variable = if_else(variable == "s(week.2)", "season", variable),
         variable = if_else(variable == "s(lag)", "lag", variable),
         variable = if_else(variable == "hours", "effort", variable)) %>%
  knitr::kable(caption = "Table 4. Model results for the most best model of visual recapture")
```

